### ISSUE TITLE
paper-radio-group-changed not firing when a radio button is deselected

### ISSUE THREAD

**Issue by lee101** [PolymerElements/paper-radio-group#14]
I'm trying to handle events with the radio group.

In my case the radio group is optional so i would like to handle the deselect event.

My first attempt was
```
companiesMenu.addEventListener('paper-radio-group-changed', function (evt) {
    var selected = companiesMenu.selected;
    if (!selected) {
        return self.searchChanged({
            company: 'all'
        })
    }
    self.searchChanged({
        company: selected
    })
});
```

The problem with this is that the event doesn't fire when a radio button is deselected.

I got around the problem by listening for the `iron-change` event on all the paper-radio-button's and skipping when something is turned off only to turn another element on.

e.g.

```
function addItemChangeHandler(item) {
    item.addEventListener('iron-change', function (evt) {
        var checked = item.checked;
        if (!checked) {
            if (companiesMenu.selected !== item.getAttribute('name')) {
                //deselect is triggered by changing selection
                return;
            }
            return self.searchChanged({
                company: 'all'
            })
        }
        self.searchChanged({
            company: item.getAttribute('name')
        })
    });
}
for (var itemIdx = 0; itemIdx < companiesMenu.items.length; itemIdx++) {
    var item = companiesMenu.items[itemIdx];
    addItemChangeHandler(item)
}
```

I think `paper-radio-group` would expose a cleaner API if it fired when things where deselected

**Comment by notwaldorf** [comment]
I think the behaviour you are trying to achieve is incorrect. Currently there is a bug that allows you to de-select a radio-button inside the `paper-radio-group` (thus leaving it with no selections). This shouldn't happen (native radio groups don't allow it either, see the spec: http://www.w3.org/TR/html401/interact/forms.html#form-controls), and should be fixed with https://github.com/PolymerElements/paper-radio-group/pull/9

Once that lands, deselection will only happen because a different selection was made, and that would fire an `paper-radio-group-changed` event.

If you want a truly "optional" radio-group, then unfortunately `paper-radio-group` isn't the right element :(

**Comment by lee101** [comment]
Looks like you're right about the specs, perhaps something like `paper-menu` could be appropriate for my use case.

However I do like optional radio groups,
I like radio groups because radios are visually more obvious there can be only one thing selected, and i like them optional because having nothing selected or deselecting something i think is easier than finding the "NA" option and selecting it, so it makes it easier for users to skip optional parts of a form.

Hopefully someone will build an optional `paper-radio-group` for me :)

**Comment by lee101** [comment]
I understand there are people who want the behaviour from the spec, perhaps having to explicitly set some kind of optional flag on the `paper-radio-group` would work for people like me?
