### ISSUE TITLE
Why padding in paper-radio-group?

### ISSUE THREAD

**Issue by dballesteros7** [PolymerElements/paper-radio-group#27]
When putting paper-radio-button elements together vertically in a paper-radio-group, one gets something like this:

![kex3bkxghwm](https://cloud.githubusercontent.com/assets/1774523/9169522/edaafba8-3f5b-11e5-853f-8a8d5e1b72c9.png)
```HTML

<div>Top</div>
<paper-radio-group style="display: flex; flex-direction: column;">
  <paper-radio-button>A</paper-radio-button>
  <paper-radio-button>B</paper-radio-button>
  <paper-radio-button>C</paper-radio-button>
  <paper-radio-button>D</paper-radio-button>
</paper-radio-group>
<div>Bottom</div>
```

The separation between the outer elements and the inner radios is half, because contiguous padding is not collapsed as contiguous margins. I think it would be better to have margins and that way have a constant separation inside and outside the group. Just a suggestion, I'd be happy to know if there is a strong reason to use padding.

**Comment by notwaldorf** [comment]
It's just there to make the radio group look better. Without any padding, the radio-buttons look pretty squished together:
<img width="123" alt="screen shot 2015-08-10 at 10 15 05 am" src="https://cloud.githubusercontent.com/assets/1369170/9177841/b7861368-3f48-11e5-8c51-58878bdf2f19.png">

I'm not sure why we prefer padding over margin (/cc @frankiefu for insight), but since the padding is applied to the content directly, to remove it/modify it you can just style the `paper-radio-button` itself, if you want:
```
paper-radio-button {
 padding: 0px;
  margin:12px;
}
```

**Comment by frankiefu** [comment]
The padding helps to increase the size of the tap target.  I think the default for radio-button is about 16x16px and usually that's too small for mobile tap/touch target.

**Comment by dballesteros7** [comment]
Thanks! That definitely satisfies my curiosity, didn't think of mobile to be honest so that's why the double whitespace in between seemed like too much :)
