### ISSUE TITLE
Weird issue on iOS

### ISSUE THREAD

**Issue by jstoup111** [PolymerElements/paper-radio-group#41]
I'm able to select all radio buttons on iOS. This only appears to happen on iOS Safari, as other desktop browsers don't appear to have this issue.

**Comment by notwaldorf** [comment]
Is this with the demo, or your custom code? I've just tried the `paper-radio-group` demo (https://elements.polymer-project.org/elements/paper-radio-group?view=demo:demo/index.html&active=paper-radio-group) on an iPhone, on both Chrome and Safari, it works fine and identically.

If it's your custom code, would you mind posting your code snippet so that we can look at it? Thanks

**Comment by jstoup111** [comment]
Hi thank you for the response. I just updated to the latest and it didn't resolve the issue. Very strange as I only notice it on iOS9 (haven't tested the others). Chrome/Safari/Firefox works fine. No console errors on iOS either.

I'm using Meteor to build the element which uses handlebars.

```
<paper-radio-group label="{{label}}" id="{{name}}">
      {{#each filteredSelectOptions}}
        <paper-radio-button name="{{value}}">{{value}}</paper-radio-button>
      {{/each}}
    </paper-radio-group>
```

**Comment by jstoup111** [comment]
Any ideas on this?

**Comment by notwaldorf** [comment]
I'm not sure where to go with this -- is it possible that this is a meteor issue on IOS9? Maybe their handlebars and the Polymer handlebars aren't mixing well together? I don't know how you get these `value`s populated either --they must be distinct, if you want the control to work correctly.

Here is a jsbin with a plain radio group, and one that uses just the polymer bindings:http://jsbin.com/xomuna/edit?html,output. 

Since this works alright, I think the problem lies with your meteor bindings (and where the `value` is generated from), so I think you need to inspect the produced DOM and see what's up.

**Comment by jstoup111** [comment]
I think it's a handlebars conflict as you mentioned. The strange thing I notice when selecting on iOS is that the paper-ripple gets halfway through it's event before it stops. Looks like the event never completes and the ripple stays. 

![image](https://cloud.githubusercontent.com/assets/1585332/11695907/ebb06b68-9e6e-11e5-9d76-77a5b2e5c45e.png)

**Comment by notwaldorf** [comment]
I'm going to close this since it doesn't look like it's a Polymer issue, and there's nothing we can really do to fix it :(

**Comment by notwaldorf** [comment]
@jstoup111 it's probably that the `name="{{value}}"` is incorrect, so the radio group is failing somewhere in selecting the next button

**Comment by jstoup111** [comment]
Thank you for the insight. Seems strange it's only an issue on iOS. Thankyou!
